### ISSUE TITLE
Sort after solve time if score is equal

### ISSUE THREAD

**Issue by JoKrus** [amochtar/aoc-ranking#7]
For occurences where the score is set to 0, because of an issue that happened, it would be nice to try and sort everyone by the solve time as second parameter to still be able to see who finished the exercise first and so on

**Comment by amochtar** [comment]
I'm actually following what adventofcode.com is doing. On equal score, sorting is determined by user id, where the lower id is ranked higher. I'd like to keep it that way, so my chart matches the leaderboard.

I did recently added a hover card that shows the ranking based on completion time for that user on that day.

**Comment by JoKrus** [comment]
Fair point, it behaves a bit misleading at the moment for my private leaderboard if I sort after score per day since the silver star was given to the 7th place since he is sorted there.

Thanks for the quick reply though!

**Comment by jhenninger** [comment]
Unfortunately the default sorting order (by IDs) makes this years visualization very hard to read. Since nobody got points on day one there are a lot of lines criss-crossing. Here's a screenshot of my leaderboard, names have been blurred for privacy:

![leaderboard](https://user-images.githubusercontent.com/197274/101194974-09d9e500-365f-11eb-8121-38b61197e315.png)

Without hovering over a single line, it's pretty much impossible to tell which user it belongs to.

**Comment by amochtar** [comment]
It's indeed unfortunate that it happened on day 1, that makes it messy. I'll see what I can do. Maybe leave out day 1 completely, or treat it differently.

**Comment by logist** [comment]
See pull request #8

**Comment by logist** [comment]
![image](https://user-images.githubusercontent.com/689697/101428234-6cc7c680-3954-11eb-9b8f-c09d0b20fc70.png)

**Comment by logist** [comment]
Actually we can probably just always sort by time and then by ID if times are the same
